### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by gg-info** [Manassehalt/2425_ESE_Projet_Torero#2]
# !! LISTE A FAIRE !!

- [x] Regarder pour encodeurs 
- [x] Reprendre régulateur 5V (entrée à gauche et sortie à droite) 
- [x] VDDA pas alimenté 
- [x] Calculer valeur R pour les leds d'état 
- [x] supprimer label hiérarchique 7.2V 
- [x] Merge les feuilles pour moteur afin de modifier les deux à la fois 
- [x] faire symbole tof 
- [x] remplir valeur composants 
- [x] Renommer comme il faut pins de communication accélero 
- [x] Remplir le readme avec les schémas + calculs + présentation globale (ne pas avoir à aller chercher les fichiers à gauche à droite)
- [ ] #3
- [x] valeur R 2k3 plutôt que 2.3k  
- [x] valeur C 100n plutôt que 0.1µF  
- [x] Rendre l'ensemble plus clair (label et autre) 

### Description du PCB :

- [x] PCB 54mm x 57mm
- [x] 4 trou de fixation a 4mm du bord Taille M3 
- [x] Remplacer l'empreinte de l'interrupteur pour le deporter hors du PCB 
- [x] condo proche 
- [x] reverifier empreinte condo imperial 
- [x] mettre port ldidar a coté de l'alimentation 5V
- [x] orientation serio j201 
- [x] en dernier les gpio pour le routage
- [x] router en premier les signaux rapides comme oscillateur, puis connecteur j201
- [x] plan de masse unique ideal
- [x] plan alim en 3,3V
- [x] changer empreinte grosse bobine 
- [x] 7.2V refaire connection (pas le meme tag) 
- [x] interrupteur a refaire empeinte plus petite 
- [x] refaire alim en suivant doc conseillé / 3 via 
- [x] Inverser pin driver moteur +zone de connexion plutot que piste 
- [x] rapprocher pastilles de ground et alim des vias associé 
- [x] aligner les composants 
- [x] Rapprocher la partie puissance (driver moteur) 
- [x] regarder plan pour retirer les antennes 
- [x] découplage 
- [x] plan sur grosse bobine 
- [x] agrandir piste gros courant 
  Routage :
- [x] Changement règle du CI -> diamètre mini via 0.45
		       -> diamètre mini anneaux 0.075
		       -> voir avec prof pour confirmer modifs (via copié depuis   correction fiack)
- [x] #5

### MECANIQUE:

- [ ] designer le parchoc qui porte les capteur de bord 
- [ ] designer les support ajustable
- [ ] imprimer les pieces du robot

### SOFTWARE:

- [ ] piloter les driver moteurs
- [ ] #4
- [ ] recevoir les donnés du lidar et les interpréter
- [ ] recevoir les donnés de l'accelerometre
- [ ] recevoir les donnés des capteurs de bords
- [ ] realiser les comportement en odometrie
- [ ] #6
- [ ] #7
